version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.8
    pre_build:
        commands:
            - yum install -y yum-utils
            - yum-builddep -y python3
            - pip install -r requirements.txt
            - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/0.12.17/hashicorp.repo
            - yum update -y
            - yum install -y terraform
    build:
        commands:
            - echo "build starting stage"
            - terraform init
            - terraform apply -auto-approve
            
    
        
        
